#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
module RJSON
  class Parser < Racc::Parser


  require 'rjson/handler'

  attr_reader :handler

  def initialize tokenizer, handler = Handler.new
    @tokenizer = tokenizer
    @handler   = handler
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
    handler
  end
##### State transition tables begin ###

racc_action_table = [
    20,    40,    20,    41,    10,    19,    18,    19,     8,    38,
     9,    18,    20,    34,    35,    36,    37,    19,    43,   nil,
     8,    25,     9,    20,    34,    35,    36,    37,    19,   nil,
   nil,     8,   nil,     9,    20,    34,    35,    36,    37,    19,
   nil,   nil,     8,    25,     9 ]

racc_action_check = [
     6,    12,    40,    16,     1,     6,    12,    40,     0,    10,
     0,     6,    41,    41,    41,    41,    41,    41,    22,   nil,
    41,    22,    41,    43,    43,    43,    43,    43,    43,   nil,
   nil,    43,   nil,    43,     7,     7,     7,     7,     7,     7,
   nil,   nil,     7,     7,     7 ]

racc_action_pointer = [
    -2,     4,   nil,   nil,   nil,   nil,    -2,    32,   nil,   nil,
     9,   nil,    -7,   nil,   nil,   nil,    -6,   nil,   nil,   nil,
   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     0,    10,   nil,    21,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -47,   -47,    -1,    -2,    -3,    -4,    -7,   -22,   -27,   -29,
   -47,    -5,    -9,    -8,   -11,   -14,   -18,   -19,   -30,   -45,
   -46,   -20,   -24,   -23,   -26,   -28,   -33,   -34,   -35,   -36,
   -37,   -38,   -39,   -40,   -41,   -42,   -43,   -44,    50,    -6,
   -10,   -17,   -21,   -25,   -12,   -13,   -15,   -16,   -31,   -32 ]

racc_goto_table = [
    23,    26,    21,    11,    15,    13,    16,    22,     1,    39,
    24,     2,     3,     4,     5,    12,    14,    42,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    46,    48,    49,    45,    44,
    16 ]

racc_goto_check = [
    14,    13,    16,     7,    11,     9,    12,    17,     1,     7,
    18,     2,     3,     4,     5,     8,    10,    16,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    14,    13,    14,    13,    11,     9,
    12 ]

racc_goto_pointer = [
   nil,     8,    11,    12,    13,    14,   nil,    -3,     9,    -1,
    10,    -2,     0,    -6,    -7,   nil,    -5,     0,     3,   nil,
   nil ]

racc_goto_default = [
   nil,   nil,    28,    29,    31,    30,     6,   nil,   nil,   nil,
   nil,   nil,    32,   nil,    17,     7,   nil,   nil,   nil,    27,
    33 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  2, 16, :_reduce_none,
  3, 16, :_reduce_none,
  1, 18, :_reduce_none,
  2, 18, :_reduce_none,
  2, 18, :_reduce_none,
  3, 18, :_reduce_none,
  2, 18, :_reduce_none,
  3, 24, :_reduce_none,
  3, 22, :_reduce_none,
  1, 22, :_reduce_none,
  3, 25, :_reduce_none,
  3, 23, :_reduce_none,
  2, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  2, 17, :_reduce_none,
  3, 17, :_reduce_none,
  1, 19, :_reduce_none,
  2, 19, :_reduce_none,
  2, 19, :_reduce_none,
  3, 19, :_reduce_none,
  2, 19, :_reduce_none,
  1, 29, :_reduce_27,
  1, 30, :_reduce_28,
  1, 20, :_reduce_29,
  1, 21, :_reduce_30,
  3, 32, :_reduce_none,
  3, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_40,
  1, 34, :_reduce_41,
  1, 34, :_reduce_42,
  1, 34, :_reduce_43,
  1, 34, :_reduce_44,
  1, 28, :_reduce_45,
  1, 26, :_reduce_46 ]

racc_reduce_n = 47

racc_shift_n = 50

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :NUMBER => 3,
  :TRUE => 4,
  :FALSE => 5,
  :NULL => 6,
  :CORRUPTED => 7,
  "," => 8,
  ":" => 9,
  "[" => 10,
  "]" => 11,
  "{" => 12,
  "}" => 13 }

racc_nt_base = 14

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "NUMBER",
  "TRUE",
  "FALSE",
  "NULL",
  "CORRUPTED",
  "\",\"",
  "\":\"",
  "\"[\"",
  "\"]\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "document",
  "object",
  "array",
  "incomplete_object",
  "incomplete_array",
  "start_object",
  "end_object",
  "pairs",
  "corrupted_pair",
  "corrupted_pairs",
  "pair",
  "string",
  "value",
  "corrupted",
  "start_array",
  "end_array",
  "values",
  "corrupted_values",
  "scalar",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

def _reduce_27(val, _values, result)
 @handler.start_array
    result
end

def _reduce_28(val, _values, result)
 @handler.end_array
    result
end

def _reduce_29(val, _values, result)
 @handler.start_object
    result
end

def _reduce_30(val, _values, result)
 @handler.end_object
    result
end

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

def _reduce_40(val, _values, result)
 @handler.scalar val[0]
    result
end

def _reduce_41(val, _values, result)
 n = val[0]; result = n.count('.') > 0 ? n.to_f : n.to_i
    result
end

def _reduce_42(val, _values, result)
 result = true
    result
end

def _reduce_43(val, _values, result)
 result = false
    result
end

def _reduce_44(val, _values, result)
 result = nil
    result
end

def _reduce_45(val, _values, result)
 result = :corrupted
    result
end

def _reduce_46(val, _values, result)
 @handler.scalar val[0].gsub(/^"|"$/, '')
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module RJSON
