#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
module RJSON
  class Parser < Racc::Parser


  require 'rjson/handler'

  attr_reader :handler

  def initialize tokenizer, handler = Handler.new
    @tokenizer = tokenizer
    @handler   = handler
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
    handler
  end
##### State transition tables begin ###

racc_action_table = [
    21,    40,    21,    41,    10,    20,    17,    20,     8,    38,
     9,    17,    21,    33,    34,    35,    36,    20,    43,   nil,
     8,    24,     9,    21,    33,    34,    35,    36,    20,   nil,
   nil,     8,   nil,     9,    21,    33,    34,    35,    36,    20,
   nil,   nil,     8,    24,     9 ]

racc_action_check = [
     6,    12,    40,    16,     1,     6,    12,    40,     0,    10,
     0,     6,    41,    41,    41,    41,    41,    41,    23,   nil,
    41,    23,    41,    43,    43,    43,    43,    43,    43,   nil,
   nil,    43,   nil,    43,     7,     7,     7,     7,     7,     7,
   nil,   nil,     7,     7,     7 ]

racc_action_pointer = [
    -2,     4,   nil,   nil,   nil,   nil,    -2,    32,   nil,   nil,
     9,   nil,    -7,   nil,   nil,   nil,    -6,   nil,   nil,   nil,
   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     0,    10,   nil,    21,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -45,   -45,    -1,    -2,    -3,    -4,    -7,   -20,   -22,   -24,
   -45,    -5,    -9,    -8,   -11,   -14,   -17,   -25,   -26,   -27,
   -43,   -44,   -18,   -21,   -23,   -29,   -30,   -31,   -32,   -33,
   -34,   -35,   -36,   -38,   -39,   -40,   -41,   -42,    48,    -6,
   -10,   -16,   -19,   -37,   -12,   -13,   -15,   -28 ]

racc_goto_table = [
    25,    19,    22,    13,    15,    18,    11,    23,    14,     1,
     2,     3,    39,     4,     5,    12,   nil,   nil,    42,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    46,    19,    47,    44,    45,    18 ]

racc_goto_check = [
    13,    18,    15,     9,    11,    17,     7,    16,    10,     1,
     2,     3,     7,     4,     5,     8,   nil,   nil,    15,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    13,    18,    13,     9,    11,    17 ]

racc_goto_pointer = [
   nil,     9,    10,    11,    13,    14,   nil,     0,     9,    -3,
     2,    -2,   nil,    -7,   nil,    -5,     0,    -1,    -5,   nil,
   nil ]

racc_goto_default = [
   nil,   nil,    27,    28,    30,    29,     6,   nil,   nil,   nil,
   nil,   nil,    16,   nil,     7,   nil,   nil,    31,    37,    26,
    32 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  2, 16, :_reduce_none,
  3, 16, :_reduce_none,
  1, 18, :_reduce_none,
  2, 18, :_reduce_none,
  2, 18, :_reduce_none,
  3, 18, :_reduce_none,
  2, 18, :_reduce_none,
  3, 24, :_reduce_none,
  3, 22, :_reduce_none,
  1, 22, :_reduce_none,
  3, 25, :_reduce_none,
  2, 23, :_reduce_none,
  1, 23, :_reduce_none,
  2, 17, :_reduce_none,
  3, 17, :_reduce_none,
  1, 19, :_reduce_none,
  2, 19, :_reduce_none,
  1, 28, :_reduce_22,
  1, 29, :_reduce_23,
  1, 20, :_reduce_24,
  1, 21, :_reduce_25,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  3, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_36,
  0, 34, :_reduce_none,
  1, 34, :_reduce_38,
  1, 34, :_reduce_39,
  1, 34, :_reduce_40,
  1, 34, :_reduce_41,
  1, 34, :_reduce_none,
  1, 32, :_reduce_43,
  1, 31, :_reduce_44 ]

racc_reduce_n = 45

racc_shift_n = 48

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :NUMBER => 3,
  :TRUE => 4,
  :FALSE => 5,
  :NULL => 6,
  :CORRUPTED => 7,
  "," => 8,
  ":" => 9,
  "[" => 10,
  "]" => 11,
  "{" => 12,
  "}" => 13 }

racc_nt_base = 14

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "NUMBER",
  "TRUE",
  "FALSE",
  "NULL",
  "CORRUPTED",
  "\",\"",
  "\":\"",
  "\"[\"",
  "\"]\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "document",
  "object",
  "array",
  "incomplete_object",
  "incomplete_array",
  "start_object",
  "end_object",
  "pairs",
  "corrupted_pair",
  "corrupted_pairs",
  "pair",
  "key",
  "value",
  "start_array",
  "end_array",
  "values",
  "string",
  "corrupted",
  "scalar",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

def _reduce_22(val, _values, result)
 @handler.start_array
    result
end

def _reduce_23(val, _values, result)
 @handler.end_array
    result
end

def _reduce_24(val, _values, result)
 @handler.start_object
    result
end

def _reduce_25(val, _values, result)
 @handler.end_object
    result
end

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

def _reduce_36(val, _values, result)
 @handler.scalar val[0]
    result
end

# reduce 37 omitted

def _reduce_38(val, _values, result)
 n = val[0]; result = n.count('.') > 0 ? n.to_f : n.to_i
    result
end

def _reduce_39(val, _values, result)
 result = true
    result
end

def _reduce_40(val, _values, result)
 result = false
    result
end

def _reduce_41(val, _values, result)
 result = nil
    result
end

# reduce 42 omitted

def _reduce_43(val, _values, result)
 result = :corrupted
    result
end

def _reduce_44(val, _values, result)
 @handler.scalar val[0].gsub(/^"|"$/, '')
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module RJSON
